# Generated by Django 4.2.28 on 2026-03-03 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signlang_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='signlang_app.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(blank=True, max_length=20, null=True)),
                ('rating', models.FloatField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, max_length=20, null=True)),
                ('USERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='signlang_app.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compalaint', models.CharField(blank=True, max_length=20, null=True)),
                ('complaintnum', models.IntegerField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, max_length=20, null=True)),
                ('USERID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='signlang_app.usertable')),
            ],
        ),
    ]
