# Generated by Django 4.2.28 on 2026-03-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlang_app', '0002_usertable_feedbacktable_complainttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainttable',
            name='complaintnum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
