# Generated by Django 4.2.28 on 2026-03-03 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signlang_app', '0003_alter_complainttable_complaintnum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complainttable',
            name='complaintnum',
        ),
    ]
