# Generated by Django 4.2.28 on 2026-03-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlang_app', '0005_alter_complainttable_date_alter_feedbacktable_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainttable',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
