# Generated by Django 4.2.28 on 2026-03-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlang_app', '0006_alter_complainttable_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainttable',
            name='reply',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
