# Generated by Django 4.2.28 on 2026-03-06 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signlang_app', '0007_complainttable_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complainttable',
            old_name='compalaint',
            new_name='complaint',
        ),
    ]
