# Generated by Django 4.2.28 on 2026-03-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlang_app', '0008_rename_compalaint_complainttable_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacktable',
            name='rating',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
