# Generated by Django 4.2.28 on 2026-03-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlang_app', '0009_alter_feedbacktable_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
