# Generated by Django 4.2.28 on 2026-03-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlang_app', '0010_alter_usertable_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainttable',
            name='complaint',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complainttable',
            name='reply',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
