# Generated by Django 4.2.28 on 2026-03-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlang_app', '0011_alter_complainttable_complaint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacktable',
            name='feedback',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
