# Generated by Django 4.2.27 on 2026-08-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlang_app', '0012_alter_feedbacktable_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacktable',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
